<?php if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_55d8e41b0e7ff',
	'title' => 'Page Builder',
	'fields' => array (
		array (
			'key' => 'field_55d9e37e1ab6f',
			'label' => 'Choose your page',
			'name' => 'sel_template',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'collection' => 'Collection Page',
				'editorial' => 'Main Editorial Page',
				'section' => 'Section in Editorial Page',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_55d8e46a181c0',
			'label' => 'Header Image',
			'name' => 'header_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'large',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_55d8e4fc181c3',
			'label' => 'Logo Collection',
			'name' => 'collection_logo',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55d9e37e1ab6f',
						'operator' => '==',
						'value' => 'collection',
					),
				),
			),
			'wrapper' => array (
				'width' => 35,
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_55d8e523181c4',
			'label' => 'Collection Title',
			'name' => 'collection_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55d9e37e1ab6f',
						'operator' => '==',
						'value' => 'collection',
					),
				),
			),
			'wrapper' => array (
				'width' => 35,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55d8eef12df5d',
			'label' => 'Title & Caption Color',
			'name' => 'text_color',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55d9e37e1ab6f',
						'operator' => '==',
						'value' => 'editorial',
					),
				),
			),
			'wrapper' => array (
				'width' => 30,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'black' => 'Black',
				'white' => 'White',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_55d8e499181c1',
			'label' => 'Caption',
			'name' => 'page_caption',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55d9e37e1ab6f',
						'operator' => '==',
						'value' => 'editorial',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 4,
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55d8e4ca181c2',
			'label' => 'Video Link',
			'name' => 'link_video',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55d9e37e1ab6f',
						'operator' => '==',
						'value' => 'collection',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_55d8e44b181bf',
			'label' => 'Page Blocks',
			'name' => 'page_blocks',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55d9e37e1ab6f',
						'operator' => '==',
						'value' => 'section',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Content',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '55d8e44f7626a',
					'name' => 'text_2_col',
					'label' => 'Columns Text',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_55d9d820d94aa',
							'label' => 'Column Left',
							'name' => 'text_col_1',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_55d9d8a5d94ac',
							'label' => 'Column Right',
							'name' => 'text_col_2',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 50,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '55d9d8bfd94ad',
					'name' => 'text_4_col',
					'label' => 'Cards',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_55d9d8dad94ae',
							'label' => 'Description',
							'name' => 'card_desc',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => 4,
							'new_lines' => 'br',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '55d9d91fd94af',
					'name' => 'grid',
					'label' => 'Grid',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_55d9d931d94b0',
							'label' => 'Images',
							'name' => 'grid_img',
							'type' => 'gallery',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '55d9d94ad94b1',
					'name' => 'row_thumbs',
					'label' => 'Row of Thumbnails',
					'display' => 'table',
					'sub_fields' => array (
						array (
							'key' => 'field_55d9dc94d4300',
							'label' => 'Row',
							'name' => 'row_img',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => 'Add Row',
							'sub_fields' => array (
								array (
									'key' => 'field_55d9d95fd94b2',
									'label' => 'Number of Columns',
									'name' => 'sel_col',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 10,
										'class' => '',
										'id' => '',
									),
									'choices' => array (
										'half' => 'Two',
										'third' => 'Three',
									),
									'default_value' => array (
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'ajax' => 0,
									'placeholder' => '',
									'disabled' => 0,
									'readonly' => 0,
								),
								array (
									'key' => 'field_55d9d99ed94b3',
									'label' => 'Image 1',
									'name' => 'col_img_1',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 30,
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'medium',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'key' => 'field_55d9d9c0d94b4',
									'label' => 'Image 2',
									'name' => 'col_img_2',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => 30,
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'medium',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'key' => 'field_55d9da0ed94b5',
									'label' => 'Image 3',
									'name' => 'col_img_3',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_55d9d95fd94b2',
												'operator' => '==',
												'value' => 'third',
											),
										),
									),
									'wrapper' => array (
										'width' => 30,
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'medium',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '55d9db39d94bf',
					'name' => 'slider',
					'label' => 'Slider',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_55d9db43d94c0',
							'label' => 'Images',
							'name' => 'slider_img',
							'type' => 'gallery',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '55d9db66d94c1',
					'name' => 'socials',
					'label' => 'Socials',
					'display' => 'row',
					'sub_fields' => array (
					),
					'min' => '',
					'max' => '',
				),
			),
		),
		array (
			'key' => 'field_55d9e510b0946',
			'label' => 'Images',
			'name' => 'collection_img',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55d9e37e1ab6f',
						'operator' => '==',
						'value' => 'collection',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-modular.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'custom_fields',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'author',
		7 => 'format',
		8 => 'featured_image',
		9 => 'categories',
		10 => 'tags',
		11 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

endif;
